language: go

go:
  - 1.8

dist: trusty
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - parallel

env:
  global:
    - DOCKER_COMPOSE_VERSION="1.13.0"
    - PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - PROJECT_NAME=transparent-keyserver

before_install:

install:
  - go get github.com/golang/lint/golint
  - go get github.com/kisielk/errcheck
  - go get github.com/fzipp/gocyclo
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/client9/misspell/cmd/misspell
  - go get ./...
script:
  - make
  - make travis-presubmit
  - ./coverage.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    script:
      - openssl aes-256-cbc -K $encrypted_a1eb99cfc21e_key -iv $encrypted_a1eb99cfc21e_iv
        -in credentials.tar.gz.enc -out credentials.tar.gz -d
      - curl https://sdk.cloud.google.com | bash
      - gcloud --quiet version
      - gcloud --quiet components update kubectl
      - gcloud auth activate-service-account --key-file client-secret.json
      - gcloud config set project ${PROJECT_NAME}
      - ./scripts/deploy.sh
