version: "3"
services:
  db:
    image: gdbelvin/trillian_db:latest
    # volumes:
      #   - /usr/local/var/mysql/:/var/lib/mysql
    restart: always

  trillian-log:
    depends_on:
      - db
    image: gdbelvin/trillian_log_server:latest
    restart: always
    ports:
      - "8090:8090" # rpcs
      - "8091:8091" # metrics
    environment:
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod 

  trillian-log-signer:
    depends_on:
      - db
    image: gdbelvin/trillian_log_signer:latest
    restart: always
    ports:
      - "8092:8091" # metrics
    environment:
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod 

  trillian-map:
    depends_on:
      - db
    image: gdbelvin/trillian_map_server:latest
    restart: always
    ports:
      - "8093:8090" # rpcs
      - "8094:8091" # metrics
    environment:
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod 

  kt-server:
    depends_on:
      - db
      - trillian-log
      - trillian-map
    image: gdbelvin/keytransparency-server:latest
    restart: always
    ports:
      - "8080:8080" # json & grpc
    environment:
      LOG_ID: 8879615737060686335
      LOG_URL: trillian-log:8090
      MAP_ID: 5481216947005239739
      MAP_URL: trillian-map:8090
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod 

  kt-signer:
    depends_on:
      - db
      - trillian-log
      - trillian-map
    image: gdbelvin/keytransparency-signer:latest
    restart: always
    environment:
      LOG_ID: 8879615737060686335
      LOG_URL: trillian-log:8090
      MAP_ID: 5481216947005239739
      MAP_URL: trillian-map:8090
      DB_HOST: db:3306
      DB_DATABASE: test
      DB_USER: test
      DB_PASSWORD: zaphod 



