---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kt-server
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: kt-server
    spec:
      containers:
      - name: kt-server
        image: us.gcr.io/transparent-keyserver/keytransparency-server
        ports:
          - containerPort: 8080
            name: json-grpc
        env:
            - name: LOG_URL
              value: trillian-log:8090
            - name: MAP_URL
              value: trillian-map:8090
            - name: MYSQL_USER
              value: test
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_PASSWORD
              value: zaphod
            - name: DB_HOST
              value: mysql:3306
---
apiVersion: v1
kind: Service
metadata:
  name: kt-server
  labels:
    run: kt-server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: json-grpc
  selector:
    run: kt-server
---
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kt-signer
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: kt-signer
    spec:
      containers:
      - name: kt-signer
        image: us.gcr.io/transparent-keyserver/keytransparency-signer
        ports:
          - containerPort: 8080
            name: json-grpc
        env:
            - name: LOG_URL
              value: trillian-log:8090
            - name: MAP_URL
              value: trillian-map:8090
            - name: MYSQL_USER
              value: test
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_PASSWORD
              value: zaphod
            - name: DB_HOST
              value: mysql:3306
            - name: LOG_KEY
              value: /trillian/log-rpc-server.pubkey.pem
            - name: SIGN_KEY
              value: /trillian/log-rpc-server.privkey.pem
            - name: SIGN_KEY_PW
              value: towel